import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";


export type PdfPayload = {
  booking_code: string;
  submittedAt: string;
  customer_name: string;
  mobile_1: string;
  mobile_2?: string | null;
  email: string;
  car_model: string;
  trip_location: string;
  trip_date: string;
  pickup_location: string;
  pickup_time: string;
  return_date: string;
  return_time: string;
  address_proof_type: string;
  deposit_doc_type: string;
  signature_name: string;
};

const GREEN = rgb(0.024, 0.306, 0.165); // #064E3B
const GRAY = rgb(0.4, 0.4, 0.4);
const BLACK = rgb(0, 0, 0);
const LINK = rgb(0.05, 0.4, 0.8);
const LIGHT = rgb(0.94, 0.98, 0.95);

export async function buildBookingPdf(p: PdfPayload): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`Sway Sarthi Booking ${p.booking_code}`);
  pdf.setAuthor("Sway Sarthi Cars Rental");
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const italic = await pdf.embedFont(StandardFonts.HelveticaOblique);

  let page = pdf.addPage([595.28, 841.89]); // A4
  const M = 50;
  let y = 800;

  const ensure = (need: number) => {
    if (y - need < 60) {
      page = pdf.addPage([595.28, 841.89]);
      y = 800;
    }
  };

  // Header band
  page.drawRectangle({ x: 0, y: 760, width: 595.28, height: 82, color: GREEN });
  page.drawText("SWAY SARTHI CARS RENTAL", { x: M, y: 810, size: 18, font: bold, color: rgb(1, 1, 1) });
  page.drawText("Customer Rental Submission Report", { x: M, y: 788, size: 11, font, color: rgb(0.9, 0.95, 0.92) });
  page.drawText(`Booking ID: ${p.booking_code}`, { x: M, y: 770, size: 10, font: bold, color: rgb(1, 1, 1) });
  y = 740;

  page.drawText(`Submitted: ${p.submittedAt} IST`, { x: M, y, size: 9, font, color: GRAY });
  y -= 24;

  const section = (title: string) => {
    ensure(36);
    page.drawRectangle({ x: M, y: y - 4, width: 495, height: 20, color: LIGHT });
    page.drawText(title, { x: M + 8, y: y + 2, size: 11, font: bold, color: GREEN });
    y -= 26;
  };

  const field = (label: string, value: string) => {
    ensure(18);
    page.drawText(label, { x: M, y, size: 9.5, font: bold, color: BLACK });
    const wrapped = wrap(value || "—", font, 9.5, 340);
    wrapped.forEach((line, i) => {
      if (i > 0) { y -= 12; ensure(14); }
      page.drawText(line, { x: M + 155, y, size: 9.5, font, color: BLACK });
    });
    y -= 16;
  };

  section("CUSTOMER DETAILS");
  field("Customer Name:", p.customer_name);
  field("Mobile Number 1:", p.mobile_1);
  field("Mobile Number 2:", p.mobile_2 || "—");
  field("Email ID:", p.email);
  field("Car Model:", p.car_model);

  section("TRIP DETAILS");
  field("Trip Location:", p.trip_location);
  field("Trip Date:", p.trip_date);
  field("Pickup Location:", p.pickup_location);
  field("Pickup Time:", p.pickup_time);
  field("Return Date:", p.return_date);
  field("Return Time:", p.return_time);

  section("TERMS & CONDITIONS ACCEPTANCE");
  paragraph(page, font, "Customer has accepted all Terms & Conditions provided by Sway Sarthi Cars Rental.", M, y, 495);
  y -= 28;
  field("Acceptance Status:", "ACCEPTED [YES]");
  field("Accepted At:", p.submittedAt + " IST");

  section("DECLARATION");
  paragraph(
    page,
    italic,
    '"I confirm that all information provided is correct and authentic."',
    M,
    y,
    495,
  );
  y -= 28;
  field("Declaration Status:", "CONFIRMED [YES]");

  section("DIGITAL SIGNATURE");
  field("Signed By:", p.signature_name);
  field("Signature Timestamp:", p.submittedAt + " IST");

  ensure(60);
  y -= 10;
  page.drawLine({ start: { x: M, y }, end: { x: M + 495, y }, thickness: 0.5, color: GRAY });
  y -= 14;
  page.drawText("SYSTEM GENERATED RECORD", { x: M, y, size: 9, font: bold, color: GREEN });
  y -= 12;
  page.drawText(
    "This document was automatically generated by the Sway Sarthi Cars Rental Submission Portal.",
    { x: M, y, size: 8.5, font, color: GRAY },
  );

  return await pdf.save();
}

function sanitize(text: string): string {
  // Map common unicode to WinAnsi-safe equivalents; drop the rest.
  return (text || "")
    .replace(/[\u2018\u2019\u201A\u2032]/g, "'")
    .replace(/[\u201C\u201D\u201E\u2033]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/[\u2022\u00B7]/g, "*")
    .replace(/\u2713/g, "[YES]")
    // strip anything outside WinAnsi printable range
    .replace(/[^\x20-\x7E\xA0-\xFF\n]/g, "?");
}

function wrap(text: string, font: PDFFont, size: number, maxW: number): string[] {
  text = sanitize(text);
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const test = line ? line + " " + w : w;
    if (font.widthOfTextAtSize(test, size) > maxW) {
      if (line) lines.push(line);
      line = w;
    } else line = test;
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function paragraph(page: PDFPage, font: PDFFont, text: string, x: number, y: number, maxW: number) {
  const lines = wrap(text, font, 10, maxW);
  lines.forEach((ln, i) => page.drawText(ln, { x, y: y - i * 12, size: 10, font, color: BLACK }));
}
