/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessBookingIdRouteImport } from './routes/success.$bookingId'
import { Route as AdminQrRouteImport } from './routes/admin.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessBookingIdRoute = SuccessBookingIdRouteImport.update({
  id: '/success/$bookingId',
  path: '/success/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/admin/qr',
  path: '/admin/qr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/qr': typeof AdminQrRoute
  '/success/$bookingId': typeof SuccessBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/qr': typeof AdminQrRoute
  '/success/$bookingId': typeof SuccessBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/qr': typeof AdminQrRoute
  '/success/$bookingId': typeof SuccessBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/qr' | '/success/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/qr' | '/success/$bookingId'
  id: '__root__' | '/' | '/admin/qr' | '/success/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminQrRoute: typeof AdminQrRoute
  SuccessBookingIdRoute: typeof SuccessBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/$bookingId': {
      id: '/success/$bookingId'
      path: '/success/$bookingId'
      fullPath: '/success/$bookingId'
      preLoaderRoute: typeof SuccessBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qr': {
      id: '/admin/qr'
      path: '/admin/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminQrRoute: AdminQrRoute,
  SuccessBookingIdRoute: SuccessBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
